### ISSUE TITLE
Header Tags  Do Not Work 

### ISSUE THREAD

**Issue by WotC-Megan** [Innervate/MTGA-forums#5]
**Describe the bug**
Header 1, Header 2, and Header 3 tags will work while you are previewing a post, but will not save when you submit. Header 3 tags work as intended. 

**To Reproduce**
* Go to forums.mtgarena.com
* Write a post reply.
* Use  header tags (1, 2, 3, 4)
* Preview the post. 
* Hit submit
* Words will not be using header tags 1, 2, and 4. 

**Expected behavior**
Header tags work as previewed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46829316/53053857-7caca880-3457-11e9-83a6-9ff43f95f7f6.png)

![image](https://user-images.githubusercontent.com/46829316/53053871-86cea700-3457-11e9-9403-4c81cb06fe39.png)

![image](https://user-images.githubusercontent.com/46829316/53053907-977f1d00-3457-11e9-95d6-8e41886f6e61.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by doman412** [comment]
Hey @WotC-Megan , we are currently investigating this issue and should have an update sometime tomorrow.

**Comment by doman412** [comment]
Hi @WotC-Megan this should be fixed! The `h1` and `h2` tags were getting removed so that test post won't update but future posts should render headers 1, 2 and 3 properly. Let me know if there are any problems or if you want the headers to be sized differently.

**Comment by WotC-Megan** [comment]
Thanks @doman412. 

The size of the font/color definitely feels off when published. I would like for the sizing when previewed to match when published, and to use any usegroup specific font coloring: 

**Post Preview:** 
![image](https://user-images.githubusercontent.com/46829316/53516490-4e475280-3a81-11e9-8dd1-93500e4e6d01.png)

**When Published:** 
![image](https://user-images.githubusercontent.com/46829316/53516429-2657ef00-3a81-11e9-937a-905ca440b162.png)

**Comment by doman412** [comment]
Hey @WotC-Megan, the headers should be updated now, there was a change that didn't get pushed live before I alerted you.
