### ISSUE TITLE
Add ESRB Rating to Forum Footer

### ISSUE THREAD

**Issue by WotC-Megan** [Innervate/MTGA-forums#6]
**Required: ESRB Rating on Forums**
MTGA recently received it's ESRB rating, and we need to have it featured on our forums, ideally in the footer area

**Describe the solution you'd like**
Current Footer: 
![image](https://user-images.githubusercontent.com/46829316/53524441-3c22df80-3a94-11e9-8793-aa818e47a154.png)

Needs to Include: 
![mtga-esrb](https://user-images.githubusercontent.com/46829316/53524551-860bc580-3a94-11e9-9b6a-ce6e86fb9fb6.png)

USE THE ABOVE IMAGE AS IS. The image includes white text/border that's hard to see in this preview, but needs to be included in the footer, e.g.: 
![image](https://user-images.githubusercontent.com/46829316/53524639-cff4ab80-3a94-11e9-9ac2-423a0031f75c.png)

**Comment by doman412** [comment]
Hey @WotC-Megan the footer has been updated with that new badge!
